# Generated by Django 2.0.4 on 2018-04-15 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodityName', models.CharField(max_length=32)),
                ('commodityIntroduce', models.CharField(max_length=128)),
                ('commodityPrice', models.IntegerField(default=0)),
                ('commodityNum', models.IntegerField(default=0)),
                ('commodityTime', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('upname', models.CharField(max_length=32)),
                ('type', models.CharField(default='', max_length=32)),
                ('state', models.CharField(default='', max_length=32)),
                ('img', models.ImageField(default='user1.jpg', upload_to='photos')),
                ('price', models.CharField(max_length=32)),
                ('tel', models.CharField(max_length=32)),
                ('remarks', models.CharField(max_length=128)),
                ('time', models.CharField(max_length=32)),
                ('result', models.CharField(default='', max_length=32)),
                ('result2', models.CharField(default='', max_length=32)),
            ],
            options={
                'db_table': 'sale',
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoppingName', models.CharField(max_length=32)),
                ('shoppingCount', models.CharField(max_length=32)),
                ('shoppingTime', models.CharField(max_length=32)),
                ('shoppingMoney', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopsName', models.CharField(max_length=32)),
                ('introduce', models.CharField(max_length=128)),
                ('phoneNumber', models.CharField(max_length=32)),
                ('registrationTime', models.CharField(max_length=32)),
                ('success_num', models.CharField(default='0', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('netname', models.CharField(default='尚未取名', max_length=32)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='shops',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='shoppingShops',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Shops'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='shoppingUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User'),
        ),
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ManyToManyField(to='app01.User'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='shops',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Shops'),
        ),
    ]
