# Generated by Django 2.0.4 on 2018-05-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180511_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='img_name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
