# Generated by Django 2.0.4 on 2018-05-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_sale_img_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zhuce_time',
            field=models.CharField(default='', max_length=32),
        ),
    ]
