# Generated by Django 2.0.4 on 2018-05-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_shudong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shudong',
            name='text',
            field=models.CharField(max_length=250),
        ),
    ]
