# Generated by Django 2.0.4 on 2018-05-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20180524_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='img',
            field=models.ImageField(default='user1.jpg', upload_to=''),
        ),
    ]
