# Generated by Django 2.0.4 on 2018-05-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20180526_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='img',
            field=models.ImageField(default='user1.jpg', upload_to=''),
        ),
    ]
