# Generated by Django 2.0.4 on 2018-06-03 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20180526_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodity',
            options={'verbose_name': '商业街店铺商品'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': '发布商品'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'verbose_name': '商业街店铺购物清单'},
        ),
        migrations.AlterModelOptions(
            name='shops',
            options={'verbose_name': '商业街店铺'},
        ),
        migrations.AlterModelOptions(
            name='shudong',
            options={'verbose_name': '树洞'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'ESchool注册用户'},
        ),
        migrations.AlterField(
            model_name='commodity',
            name='commodityIntroduce',
            field=models.CharField(max_length=128, verbose_name='商品介绍'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='commodityName',
            field=models.CharField(max_length=32, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='commodityNum',
            field=models.IntegerField(default=0, verbose_name='商品数量'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='commodityPrice',
            field=models.IntegerField(default=0, verbose_name='商品价格'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='commodityTime',
            field=models.CharField(default='', max_length=32, verbose_name='上货时间'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='shops',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Shops', verbose_name='所属店铺'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='img',
            field=models.ImageField(default='user1.jpg', upload_to='', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='img_name',
            field=models.CharField(default='', max_length=32, verbose_name='图片名称'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='name',
            field=models.CharField(max_length=32, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.CharField(max_length=32, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='remarks',
            field=models.CharField(max_length=128, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='result',
            field=models.CharField(default='', max_length=32, verbose_name='发单完成确认'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='result2',
            field=models.CharField(default='', max_length=32, verbose_name='抢单完成确认'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='state',
            field=models.CharField(default='', max_length=32, verbose_name='抢单用户'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tel',
            field=models.CharField(max_length=32, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='time',
            field=models.CharField(max_length=32, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='type',
            field=models.CharField(default='', max_length=32, verbose_name='分区'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='upname',
            field=models.CharField(max_length=32, verbose_name='发单用户'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ManyToManyField(to='app01.User', verbose_name='发布用户'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='shoppingCount',
            field=models.CharField(max_length=32, verbose_name='购买数量'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='shoppingMoney',
            field=models.CharField(default='', max_length=32, verbose_name='交易金额'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='shoppingName',
            field=models.CharField(max_length=32, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='shoppingShops',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Shops', verbose_name='所属店铺'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='shoppingTime',
            field=models.CharField(max_length=32, verbose_name='购买时间'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='shoppingUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User', verbose_name='购买用户'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='ShopsName',
            field=models.CharField(max_length=32, verbose_name='商铺名称'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='introduce',
            field=models.CharField(max_length=128, verbose_name='商铺简介'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='phoneNumber',
            field=models.CharField(max_length=32, verbose_name='客服电话'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='registrationTime',
            field=models.CharField(max_length=32, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='success_num',
            field=models.CharField(default='0', max_length=32, verbose_name='交易次数'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User', verbose_name='注册用户'),
        ),
        migrations.AlterField(
            model_name='shudong',
            name='text',
            field=models.CharField(max_length=250, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='shudong',
            name='time',
            field=models.CharField(max_length=32, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='shudong',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User', verbose_name='发布用户'),
        ),
        migrations.AlterField(
            model_name='user',
            name='netname',
            field=models.CharField(default='0', max_length=32, verbose_name='封禁状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='realname',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rtime',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='实名认证时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='studentnum',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='studentpwd',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='学校官网密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zhuce_time',
            field=models.CharField(default='', max_length=32, verbose_name='账号注册时间'),
        ),
    ]
