# Generated by Django 2.0.4 on 2018-06-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20180603_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='realname',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rtime',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='实名认证时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='studentnum',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='studentpwd',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='学校官网密码'),
        ),
    ]
