# Generated by Django 2.0.4 on 2018-07-03 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_auto_20180603_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoseAndFound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='失物名称')),
                ('upname', models.CharField(max_length=32, verbose_name='发布用户')),
                ('tel', models.CharField(max_length=32, verbose_name='联系方式')),
                ('text', models.CharField(max_length=255, verbose_name='失物备注')),
                ('type', models.CharField(max_length=32, verbose_name='发布类型')),
                ('time', models.DateField(unique_for_date=True, verbose_name='发布时间')),
                ('img', models.ImageField(default='user1.jpg', upload_to='', verbose_name='图片')),
                ('img_name', models.CharField(default='', max_length=32, verbose_name='图片名称')),
                ('count', models.IntegerField(max_length=32, verbose_name='认领人数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User', verbose_name='认领用户')),
            ],
            options={
                'verbose_name': '失物招领',
            },
        ),
    ]
