# Generated by Django 2.0.4 on 2018-07-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_loseandfound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loseandfound',
            name='count',
            field=models.CharField(max_length=32, verbose_name='认领人数'),
        ),
    ]
