# Generated by Django 2.0.4 on 2018-07-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_auto_20180703_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loseandfound',
            name='time',
            field=models.CharField(max_length=32, verbose_name='发布时间'),
        ),
    ]
