# Generated by Django 2.0.4 on 2018-07-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_auto_20180703_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loseandfound',
            name='user',
        ),
        migrations.AddField(
            model_name='loseandfound',
            name='user',
            field=models.ManyToManyField(to='app01.User', verbose_name='认领用户'),
        ),
    ]
