# Generated by Django 2.0.4 on 2018-07-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_auto_20180703_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowseCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(max_length=64, verbose_name='网站浏览次数')),
            ],
            options={
                'verbose_name': '网站浏览次数',
            },
        ),
    ]
