# Generated by Django 2.0.4 on 2018-07-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_browsecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsecount',
            name='count',
            field=models.IntegerField(default=0, max_length=64, verbose_name='网站浏览次数'),
        ),
    ]
